### ISSUE TITLE
Error after install

### ISSUE THREAD

**Issue by pcav** [trac-hacks/trac-ticketreminder#10]
After installing, opening a ticket returns the error:
`AttributeError: 'Environment' object has no attribute 'get_db_cnx`

**Comment by rjollos** [comment]
This issue was resolved in a8b116bc. Did you install from HEAD of master?

The version on PyPI needs to be updated. See #11.

**Comment by pcav** [comment]
Thanks! I installed via `pip`

**Comment by rjollos** [comment]
You can use pip to install direct from the repository as well: `pip install git+https://github.com/trac-hacks/trac-ticketreminder.git`.
