### ISSUE TITLE
Update version of plugin on PyPI

### ISSUE THREAD

**Issue by rjollos** [trac-hacks/trac-ticketreminder#11]
See also #10.

https://pypi.org/project/TicketReminderPlugin

@mitar If you grant me maintainer access on PyPI (username: rjollos) I'll publish a new version.

**Comment by rjollos** [comment]
@mitar would you consider granting me Maintainer access so that i can publish the new version?

**Comment by mitar** [comment]
Sorry, missed this before. Added you as an owner.

**Comment by rjollos** [comment]
Thanks! I've published version 0.2.1.
