### ISSUE TITLE
TypeError: format_subj() takes exactly 2 arguments (3 given)

### ISSUE THREAD

**Issue by rjollos** [trac-hacks/trac-ticketreminder#6]
Reported on the [trac-users mailing list](https://groups.google.com/forum/#!topic/trac-users/RhenSWSEmqw), 

> when command "trac-admin /path/to/trac/environment reminders" is executing, error:
> Failure sending reminder notification for ticket #11574: TypeError: format_subj() takes exactly 2 arguments (3 given).

In [[13382]](http://trac.edgewall.org/changeset/13382) / [#2259](http://trac.edgewall.org/ticket/2259) for Trac 1.0.3, the signature of `format_subj` was modified by adding a keyword argument `newticket=True`.

**Comment by mitar** [comment]
Published.
